### ISSUE TITLE
post-mvp: allow flag for hiding content tracks/lessons

### ISSUE THREAD

**Issue by wolovim** [Developer-DAO/academy-turbo#104]
we're still figuring out workflows with content partners, but it would be nice to be able to collaborate in github before the content is visible to learners.

simplest solution may just be to add a boolean tag, e.g., `isVisible`, that we can toggle off until the content is ready. would be nice for this functionality to exist on both tracks and individual lessons.

**Comment by elPiablo** [comment]
Could you give an example scenario and mention what is on a `main` branch (e.g. toggled on or off) and what is on a `working` or possibly `staging` branch. 
e.g. a track with 5 agreed lessons in a track for a partner.

**Comment by Markkos89** [comment]
Already made this with a little twist:

added new fields:

- productionVisible
- stagingVisible
- visible

**productionVisible**
works as your `isVisible` flag but only for production environment (main branch)

**stagingVisible**
works as the `isVisible` flag but only fro staging environment (staging branch)

**visible**
works as the `isVisible` flag but meant to local development stuff

The idea of the 3 flags is to switch visibility as needd among different scenarios and needs.
The most relevant scenario to mention is if you are content creator writing locally you can add the lesson to the database hidden for produciton and staging but locally visible.

**Comment by elPiablo** [comment]
I think we can close this one too @Markkos89! Nice work!

**Comment by Markkos89** [comment]
> I think we can close this one too @Markkos89! Nice work!

yes, we can. thanks piablo!
