### ISSUE TITLE
RPC provider needs changed in front-end code apps/academy/src/pages/tracks/nft-solidity/5.mdx 

### ISSUE THREAD

**Issue by elPiablo** [Developer-DAO/academy-turbo#118]
## We're trying to get D_D partner, POKT, used in our lessons. In this case, with RPC providers

- stems from this PR: https://github.com/Developer-DAO/academy-turbo/pull/119
- the front-end code in apps/academy/src/pages/tracks/nft-solidity/5.mdx imports `alchemyProvider` for WAGMI. 
- is it possible to change to import and use a POKT Network provider such as Grove or Nodies?
- [Grove](https://www.grove.city/)
- [Nodies](https://www.nodies.app/)
or 
- for D_D Grove Perks deForm click [here](https://devdao.to/grove-perk)

@kempsterrrr can you verify which of the above links would be correct for us in this instance?
- pertaining WAGMI docs: https://0.12.x.wagmi.sh/core/providers/configuring-chains hopefully can provide an answer if changing providers is possible. I'm not totally sure at a glance.

**Comment by kempsterrrr** [comment]
Can this be closed now @elPiablo ?

**Comment by elPiablo** [comment]
> Is there anything you still need from me on this @elPiablo ?

No, all good, @kempsterrrr 💯  

I thought I had sent this answer hours ago. Didn't get as far as the Comment button....
