### ISSUE TITLE
feat: update partner with academy banner

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#23]
actual banner:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/f08c721d-027d-4ab9-af60-205c9447eea3)

latest updated banner desing:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/cd530f37-bd06-49d6-8c55-2b84805409d9)

What needs to be updated is the `Reach Out` button and the Image

@wolovim @elPiablo is that image correct? thinking on those logos etc, thanks

**Comment by kempsterrrr** [comment]
Yo, nice work @peteruche21 - can we get actual partner logos here, please, folks?

Preferred partners we need to display are: Zerion, POKT Network.

Please can we avoid displaying logos for companies we're not working with?  We can add logos as more folks partner with us. Thoughts? (We have API3 coming soon and another unannounced. 

cc @wolovim

**Comment by Markkos89** [comment]
> Yo, nice work @peteruche21 - can we get actual partner logos here, please, folks?
> 
> Preferred partners we need to display are [Zerion](https://zerion.notion.site/Company-info-brand-assets-b9bfad1ef7b745a7a2e09640f6374ff1) & POKT Network (although this might ultimately be one of the RPC Gateways in their network like [Grove](https://www.grove.city/) - will confirm next week)
> 
> Please can we avoid displaying logos for companies we're not working with? We can add logos as more folks partner with us. Thoughts? (We have API3 coming soon and another unannounced.
> 
> cc @wolovim

tagging @uma-l also so he is aware of this request and can update the designs! :pray: 

@peteruche21 we can pause this task until actually we have the correct designs for doing this :wink: 

thank you @kempsterrrr for letting us know :pray:
