### ISSUE TITLE
design: update partners banner image

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#24]
screeshot: 
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/9bbcf4d3-dbdb-4f36-bc48-b5f703aa7cab)

@uma-l we need to update the partner's banner image with real partner's logos

requested here in case you missed it: https://github.com/Developer-DAO/academy-turbo/issues/23#issuecomment-1773332698
and I quote:

```
by kempsterrrr:
Preferred partners we need to display are [Zerion](https://zerion.notion.site/Company-info-brand-assets-b9bfad1ef7b745a7a2e09640f6374ff1) & POKT Network (although this might ultimately be one of the RPC Gateways in their network like [Grove](https://www.grove.city/) - will confirm next week)**

Please can we avoid displaying logos for companies we're not working with? We can add logos as more folks partner with us. Thoughts? (We have API3 coming soon and another unannounced.

```

@kempsterrrr do we have the final list? It would be nice for uma to have the final list before he starts to work on this. 

uma, on the quote you have the links to the assets

Thanks both

**Comment by kempsterrrr** [comment]
Hey @Markkos89 - there are 3 that are good to up on here now - [Zerion](https://zerion.notion.site/Company-info-brand-assets-b9bfad1ef7b745a7a2e09640f6374ff1), [POKT Network](https://www.pokt.network/press-kit/) and API3 - @billyjitsu can you provide logo's for API3 please?

**Comment by billyjitsu** [comment]
[API3 Media Kit.zip](https://github.com/Developer-DAO/academy-turbo/files/13166682/API3.Media.Kit.zip)
Here you go

**Comment by Markkos89** [comment]
hey @uma-l can you provide a new banner image with this partners assets?? At your time

thanks in advance mate!!

**Comment by Markkos89** [comment]
updated
