### ISSUE TITLE
feat: FundamentalsPage mobile design

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#37]
FundamentalsPage mobile design

screenshoot for reference:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/a0363b55-f96f-4590-b325-7eb0c10568b6)

Figma url: hfigma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=KRCAkHTm2HHZIEaM-0

**Comment by okhaimie-dev** [comment]
Just adding this here for review:

https://www.figma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=Cxsjdi2PsKHkEm4T-0
