### ISSUE TITLE
feat: new TrackDetailPage

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#39]
## TrackDetailPage layout

Layout and components structure open for the dev taking it

![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/dc33726a-b4e9-4fac-9d6b-f2489be750aa)

Please aim to build the page and components as static as you can, in later tasks we will be updating this work with dynamic integration from the backend. 

Thanks!

Figma url: https://www.figma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=sL4qGWWiJ8y2k4mr-0

**Comment by recepcankaya** [comment]
#wagmi!!!

**Comment by Markkos89** [comment]
> #wagmi!!!

assigned!

LFG @recepcankaya !!!

:smile:
