### ISSUE TITLE
Content fix: assign learner level tags to all tutorials and fundamentals

### ISSUE THREAD

**Issue by elPiablo** [Developer-DAO/academy-turbo#61]
A lot of unresolved discussion around what learner levels should be, i.e.
Beginner
Elementary or Foundational or Fundamental (all mean the same)
Intermediate
Advanced

or

Beginner
Intermediate
Advanced.

as another example: https://en.wikipedia.org/wiki/Four_stages_of_competence

1. **Beginner** : Personally and also based on the learning frameworks with broad collaboration areas that I am familiar with, a 'beginner' is someone has walked in the door, and needs tonnes of hand-holding and can't build anything themselves. But they experience everything as being relatively easy - because they haven't been confronted with deeper and broader concepts.

2. **Voldemort** : i.e. 'foundational'/'fundamental'/'elementary'/'pre-intermediate' / 'in-between' stage: 
this is where someone is aware of what they are trying to do, but can't necessarily get it to work, or they can, but with a lot of effort.
I think I'm a good example of someone at the very lower end of this scale. 

3. **Intermediate** Whereas someone at an intermediate levels is quite autonomous and confident, has good feeling and grasp for concepts, and......  can 
 explain those concepts well. They can also build projects of their own without any assistance. Can give helpful basic mentorship.
 
4. **Advanced**: knows what they are doing, knows most of the pitfalls, can automatically see where someone else is going right or wrong. Can delegate tasks without too much thought. Can really see the bigger picture as second nature. Can mentor with ease.

(5. Expert - has probably mentored many times, etc, etc. I believe we don't need a tag for this category......yet. See below)

There are various reasons for having four learning stages instead of three. 
1. learners know what we are offering them therefore builds confidence vs despair (too easy or too difficult), i.e. wasted time
2. it lets us know what is in demand
3. we have a better overview of our offering and so do potential authors/contributors - which makes (forward) planning easier for **everyone**, i.e. in traditional educations terms - building tracks and syllabuses   
4. it helps with a clear mentorship 'stack' - delegation is easier to streamline/identify, as each level can identify easily what is above and below, and is therefore an efficient and time-saving system in a decentralised work environment. 
5. when we want to invite 'Experts' to the platform, it can work for us in a couple of ways
   a. if we invite an expert to contribute to the platform in what ever capacity, whether that is textual, or as a speaker, it gives a great signal of their social standing in the space, which for others, is something to aspire to
   b. with that signalling value, also comes income
6. ...

There are many more, but just can't think of them at hand.

**Comment by Markkos89** [comment]
I would vote for;

- Beginner
- Intermediate
- Advanced.
