### ISSUE TITLE
Style Quiz component as figma design

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#68]
Figma url: https://www.figma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=Ha3XLdrnvyiXqWDd-0

The `Quiz` component is placed here:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/1d5884a7-e6f8-407c-a0d4-feafdf1f8cd5)

Desired design looks like this:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/2a1be212-3eb5-4273-b166-1cc5f93800bd)
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/83bf0a65-6dd9-4ff6-96de-5d59c364101e)

On the project, you will find the outdated component placed at `apps/academy/components/mdx/Quiz.tsx` :
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/bbb05cf1-7112-47c9-8bb3-a6c0dd442066)

When running the app, you can find the trigger button here:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/54b4c8dc-a88b-4a81-896c-7ce57baf477d)
example url: `http://localhost:3000/tracks/intro-to-ethereum/1`

and the actual outdated design looks like this:
![image](https://github.com/Developer-DAO/academy-turbo/assets/2791028/268fb71a-eede-4538-80e3-797c1bfd9269)

**Comment by Markkos89** [comment]
related PR: https://github.com/Developer-DAO/academy-turbo/pull/70

**Comment by elPiablo** [comment]
hey folks, it would be great if the all the different quiz modals were wider on the (desktop) page. Warm-up, checkpoint and final quiz. They are very narrow in comparison to the page, and it creates a feeling of being in a very different (learning) environment to the rest of the lesson.
