### ISSUE TITLE
Fix Wallet integration with t3 stack (currently throwing status 500 error code)

### ISSUE THREAD

**Issue by Markkos89** [Developer-DAO/academy-turbo#69]
There is an error being thrown when we try to connect the wallet, exactly after sign in with Siwe.
The error is an status 500 code.
You can check it while Inspecting the console in your browser.

**Comment by wolovim** [comment]
smol extra details for whoever picks this up:
the call to `/api/auth/_log` results in the status 500 and the following message:
`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

**Comment by Markkos89** [comment]
fixed on https://github.com/Developer-DAO/academy-turbo/pull/96
