### ISSUE TITLE
Widen all quiz modals  

### ISSUE THREAD

**Issue by elPiablo** [Developer-DAO/academy-turbo#90]
- it would be great if the all the different quiz modals were wider on the (desktop) page as per Figma design. I estimate they are designed to be 55-66% of the lesson body text. 

- [x] Warm-up
- [x] checkpoint questions
- [ ]  final quiz

- They are very narrow in comparison to the page, and it creates a feeling of being in a very different (learning) environment to the rest of the lesson.

**Comment by Markkos89** [comment]
@elPiablo I believe this one is already done and should be closed, can you confirm?

**Comment by elPiablo** [comment]
> @elPiablo I believe this one is already done and should be closed, can you confirm?

Hey @Markkos89 
the Warm-up and checkpoint modals (both are the same) are a really nice width:
![checkpoint](https://github.com/Developer-DAO/academy-turbo/assets/40469149/9ec66cfa-2a2b-494e-8221-f76686e2d8ba)

But the final quiz is still narrow (I don't think that is the intention from the figma - in there it also looks like it should be wide, i.e. the same width as the other quiz components)
![finalquiz](https://github.com/Developer-DAO/academy-turbo/assets/40469149/70f7699e-ff62-483c-9616-7d24381af44e)

**Comment by Markkos89** [comment]
> > @elPiablo I believe this one is already done and should be closed, can you confirm?
> 
> Hey @Markkos89 the Warm-up and checkpoint modals (both are the same) are a really nice width: ![checkpoint](https://private-user-images.githubusercontent.com/40469149/300979473-9ec66cfa-2a2b-494e-8221-f76686e2d8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTQ3NjUsIm5iZiI6MTcwNjY1NDQ2NSwicGF0aCI6Ii80MDQ2OTE0OS8zMDA5Nzk0NzMtOWVjNjZjZmEtMmEyYi00OTRlLTgyMjEtZjc2Njg2ZTJkOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDIyNDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTQzYTFmZDlhOGI5YmFiYTMxMjAzOWEwMTQ2NDcyZjZjNmVhNjdjOTBlNTE3NmI4ZDFlZmNlYTdiMjE5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jrr539gy-xM9bdIpTpx6bFnqIqYGRbW5fZ9KZ_nWIIQ)
> 
> But the final quiz is still narrow (I don't think that is the intention from the figma - in there it also looks like it should be wide, i.e. the same width as the other quiz components) ![finalquiz](https://private-user-images.githubusercontent.com/40469149/300979905-70f7699e-ff62-483c-9616-7d24381af44e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTQ3NjUsIm5iZiI6MTcwNjY1NDQ2NSwicGF0aCI6Ii80MDQ2OTE0OS8zMDA5Nzk5MDUtNzBmNzY5OWUtZmY2Mi00ODNjLTk2MTYtN2QyNDM4MWFmNDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDIyNDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYWZkMTBhY2IwNWRmNmY1OTU4NDBhMTBiYzExN2U1MjY5OTExYTU2MDMxZTZkMjZjYzA0ODA4YjMzMTNhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uue5X63wzOF-x0oxas-rC2nuL8A_S6nknmij4yvRR_o)

Ok we can modify that, either way the QuizModal has less content inside that match with the width it has right now. Making it widther will end up having a lot of space inside just for a question and some answers.
Maybe in another question with more text and with more text in the answers options will make it look small ? That can justify to increase the width of the QuizModal

**Comment by elPiablo** [comment]
> Ok we can modify that, either way the QuizModal has less content inside that match with the width it has right now. Making it widther will end up having a lot of space inside just for a question and some answers.
> Maybe in another question with more text and with more text in the answers options will make it look small ? That can justify to increase the width of the QuizModal

yes, if there is 'too little' content, and it is tall, it's going to look quite 'empty'. 

To be honest, I was thinking that if it is as wide as the other question modals, but not tall like them, how would that look? That is actually what I understood from the Figma design of the final quiz modal (I'm not referring to any Figma design of question modals)
