### ISSUE TITLE
Font is quite thick, therefore brightness emitted is very stark

### ISSUE THREAD

**Issue by elPiablo** [Developer-DAO/academy-turbo#91]
First of all, I have to apologise for coming late with these suggestions, since the designs have been here long enough. But I didn't realise the visualisation process from Figma designs to an actual living environment of a website platform.

I love the design of the original choice of font, as it looks really slick on the black background. But in reality, it is/was actually not an easy font to read, some of the rounded letters (esp. 'c' and 'o') were easily mistaken with each other. It was very taxing on the eyes and emitting a huge amount of light from the screen. And the contrast with a black background made it even more starkly bright. 

It looks like the font got changed in the last couple of days, and that was quite an improvement. But if I'm honest, it's still mega-bright. It's a lot of effort for me to keep looking at the screen for any length of time. In short, it's a distraction from the actual learning material. 

If you look at the difference with v1. It is a lot more relaxing on the eyes, because the lines of the font are much thinner, and therefore give off much less light, and there is visual space to digest the words vs the lettering.

The fonts in the modals also need a look. Everything looks like it's in bold.

**Comment by uma-l** [comment]
@elPiablo , which font? The main content font? can you please share a pic?

**Comment by uma-l** [comment]
we should use poppins font instead for all the content

**Comment by elPiablo** [comment]
> @elPiablo , which font? The main content font? can you please share a pic?

Will do @uma-l
