### ISSUE TITLE
Including POKT and Zerion in Academy

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/academy-turbo#93]
Just chatting with @elPiablo about how we include the POKT's RPC and the Zerion wallet in academy in a non-shilly way

- [x] update Web3 wallets lesson with Zerion
- [x] Replace MM for Zerion Browser Extension where used in Lessons
- [x] update RPC lesson with POKT
- [x] Where RPCs are mentioned elsewhere in lessons, linked to RPCs on POKT Network ([Grove](https://www.grove.city/), [Nodies](https://www.nodies.app/))

![image](https://github.com/Developer-DAO/academy-turbo/assets/9025997/fbb4661f-7b63-4a6e-b8e3-7dac261b3cc1)
- Connecting to a Frontend lesson contains lots of mentions of a different RPC provider - for the front-end code. This issue will address that explicitly: https://github.com/Developer-DAO/academy-turbo/issues/118, and therefore we can close this one.

**Comment by kempsterrrr** [comment]
Please can we use the relevant short-urls so we can track clicks 🙃 

Grove - https://devdao.to/grove-perk
Zerion - https://devdao.to/get-zerion

We can just use Grove for now and I can see if we can get an offer for Nodies as well

**Comment by elPiablo** [comment]
@kempsterrrr could you review this PR: https://github.com/Developer-DAO/academy-turbo/pull/101 , please?
I understand you want to gather the clicks, there's just some conflicting, or additional messy steps involved then regarding the Perks link you provided: https://devdao.to/grove-perk 

What am I talking about?

On Academy, we always encourage devs to create a separate browser profile and a separate wallet for dev work without any valuable tokens in them. Bear in mind, most of what we are expecting learners at this stage is **not** so readily to be deploying contracts for apps on a Mainnet with valuable tokens. 

The Grove Perks link is expecting you to have a D4R or 400 CODE, which would then involve a Mainnet tx with those tokens from a user's D_D wallet to their 'dev wallet' to align with our platform advice.

So far, in the RPC lesson, I suggested that the Grove Perks link be for D_D members,  I gave an alternative to non-D_D heads to use the Nodies link: https://www.nodies.app/. As I understood from the POKT site, that Grove is a paid service, and there is a free tier for Nodies, is that right?

Bottom line, we need to resolve this 'developer wallet' and RPC sign up with Perks. I would like to know what steps to give learners across multiple lessons and get that rectified. Cheers in advance for jumping in with this.

I'll just drop this same post in the PR, so the lads can see where I'm at with it.
